version: '3.7'

networks:
  app-tier:
    driver: bridge

services:

  pgsql:
    container_name: pgsql
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ${DATA_PATH}/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: saas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-tier

  influxdb:
    container_name: influxdb
    image: influxdb:2.0.6-alpine
    ports:
      - 8086:8086
    volumes:
      - ${DATA_PATH}/influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdb
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxdb
      - DOCKER_INFLUXDB_INIT_ORG=jtradeplatform
      - DOCKER_INFLUXDB_INIT_BUCKET=charts
      - DOCKER_INFLUXDB_INIT_RETENTION=30d
    networks:
      - app-tier

  redis:
    image: 'redis:6.2.3-alpine'
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - app-tier