version: '3.7'

networks:
  app-tier:
    driver: bridge

services:

  pgsql:
    container_name: pgsql
    image: postgres:13.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ${DATA_PATH}/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: saas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-tier

  influxdb:
    container_name: influxdb
    image: influxdb:2.0.6-alpine
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ${DATA_PATH}/influxdb:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=influxdb
      - DOCKER_INFLUXDB_INIT_PASSWORD=influxdb
      - DOCKER_INFLUXDB_INIT_ORG=jtradeplatform
      - DOCKER_INFLUXDB_INIT_BUCKET=saas_db
      - DOCKER_INFLUXDB_INIT_RETENTION=3d
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    networks:
      - app-tier